apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 4
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - image: docker.io/bootdotdev/synergychat-crawler:latest
          imagePullPolicy: Always
          name: synergychat-crawler
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
