apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 4
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
  namespace: crawler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - image: docker.io/bootdotdev/synergychat-crawler:latest
          imagePullPolicy: Always
          name: synergychat-crawler-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
            - name: synergychat-api-volume
              mountPath: /persist
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
        - image: docker.io/bootdotdev/synergychat-crawler:latest
          imagePullPolicy: Always
          name: synergychat-crawler-2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
            - name: synergychat-api-volume
              mountPath: /persist
          env:
            - name: CRAWLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_PORT_2
            - name: CRAWLER_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_KEYWORDS
            - name: CRAWLER_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_DB_PATH
        - image: docker.io/bootdotdev/synergychat-crawler:latest
          imagePullPolicy: Always
          name: synergychat-crawler-3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
            - name: synergychat-api-volume
              mountPath: /persist
          env:
            - name: CRAWLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_PORT_3
            - name: CRAWLER_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_KEYWORDS
            - name: CRAWLER_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_DB_PATH
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc
